### ISSUE TITLE
Research whether there is a plugin to create a static website from a mezzanine site

### ISSUE THREAD

**Issue by agstephens** [cedadev/light-migrations#9]
...and will it work on the versions we are running?

**Comment by mjpritchard** [comment]
From a quick scout around, I don't think there is. There's a thing called Pelican, but learning how to use that may be more tricky than just updating Mezzanine. Pelican is about making a static site using jinja2 templates, but you'd have to work out how to squeeze the mezzanine data model through it I think. Would probably work, but no less effort!
